dist: xenial
sudo: required
services:
- docker
cache:
  directories:
    - /home/travis/.cache/go-build
language: go
go:
- "1.11.1"
env:
- BUCKET=PPS3
branches:
  except:
    - /^v[0-9]/
before_install:
- sudo etc/testing/ci/before_install.sh
before_script:
- docker version
# Install any deps used by our "batch test" cron
# etc/testing/ci/travis_install_batch_deps.sh
script:
- etc/testing/travis.sh
after_failure:
- kubectl version
- kubectl get all
- kubectl describe pod -l app=pachd
- kubectl describe pod -l suite=pachyderm,app=etcd
notifications:
  slack: pachyderm:qmSCZSX1Q2yWxc6DjNZZFLGd
