apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-example-producer-deployment
spec:
  selector:
    matchLabels:
      app: kafka-example-producer
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka-example-producer
    spec:
      containers:
      - name: kafka-example-producer
        image: pachyderm/kafka-example-producer:latest
        ports:
        - containerPort: 80
